# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, window_main):
        window_main.setObjectName("window_main")
        window_main.resize(665, 500)
        self.centralwidget = QtWidgets.QWidget(window_main)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget = QtWidgets.QWidget(window_main)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.label_camera_output_title = QtWidgets.QLabel(self.tab_control)
        self.label_camera_output_title.setGeometry(QtCore.QRect(10, 0, 311, 16))
        self.label_camera_output_title.setObjectName("label_camera_output_title")
        self.gb_recording = QtWidgets.QGroupBox(self.tab_control)
        self.gb_recording.setGeometry(QtCore.QRect(460, 390, 191, 81))
        self.gb_recording.setObjectName("gb_recording")
        self.button_toggle_recording = QtWidgets.QPushButton(self.gb_recording)
        self.button_toggle_recording.setGeometry(QtCore.QRect(10, 40, 171, 31))
        self.button_toggle_recording.setObjectName("button_toggle_recording")
        self.label_status_title = QtWidgets.QLabel(self.gb_recording)
        self.label_status_title.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_status_title.setObjectName("label_status_title")
        self.label_status_current = QtWidgets.QLabel(self.gb_recording)
        self.label_status_current.setGeometry(QtCore.QRect(70, 20, 111, 16))
        self.label_status_current.setObjectName("label_status_current")
        self.label_camera_output = QtWidgets.QLabel(self.tab_control)
        self.label_camera_output.setGeometry(QtCore.QRect(10, 20, 640, 360))
        self.label_camera_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_camera_output.setObjectName("label_camera_output")
        self.gb_classroom = QtWidgets.QGroupBox(self.tab_control)
        self.gb_classroom.setGeometry(QtCore.QRect(220, 390, 231, 81))
        self.gb_classroom.setObjectName("gb_classroom")
        self.cb_choose_classroom = QtWidgets.QComboBox(self.gb_classroom)
        self.cb_choose_classroom.setGeometry(QtCore.QRect(110, 20, 111, 22))
        self.cb_choose_classroom.setAutoFillBackground(False)
        self.cb_choose_classroom.setEditable(True)
        self.cb_choose_classroom.setCurrentText("")
        self.cb_choose_classroom.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cb_choose_classroom.setObjectName("cb_choose_classroom")
        self.button_confirm_classroom = QtWidgets.QPushButton(self.gb_classroom)
        self.button_confirm_classroom.setGeometry(QtCore.QRect(10, 50, 211, 23))
        self.button_confirm_classroom.setObjectName("button_confirm_classroom")
        self.label_choose_classroom = QtWidgets.QLabel(self.gb_classroom)
        self.label_choose_classroom.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_choose_classroom.setObjectName("label_choose_classroom")
        self.gb_camera = QtWidgets.QGroupBox(self.tab_control)
        self.gb_camera.setGeometry(QtCore.QRect(10, 390, 201, 81))
        self.gb_camera.setObjectName("gb_camera")
        self.cb_camera_list = QtWidgets.QComboBox(self.gb_camera)
        self.cb_camera_list.setGeometry(QtCore.QRect(90, 50, 101, 22))
        self.cb_camera_list.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.cb_camera_list.setObjectName("cb_camera_list")
        self.label_choose_camera = QtWidgets.QLabel(self.gb_camera)
        self.label_choose_camera.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_choose_camera.setObjectName("label_choose_camera")
        self.button_refresh_camera_list = QtWidgets.QPushButton(self.gb_camera)
        self.button_refresh_camera_list.setGeometry(QtCore.QRect(10, 20, 181, 23))
        self.button_refresh_camera_list.setObjectName("button_refresh_camera_list")
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_result = QtWidgets.QWidget()
        self.tab_result.setObjectName("tab_result")
        # self.table_attendance_result = QtWidgets.QTableWidget(self.tab_result)
        # self.table_attendance_result.setGeometry(QtCore.QRect(10, 30, 641, 381))
        # self.table_attendance_result.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.table_attendance_result.setAlternatingRowColors(False)
        # self.table_attendance_result.setSortingEnabled(False)
        # self.table_attendance_result.setObjectName("table_attendance_result")
        # self.label_attendance_result = QtWidgets.QLabel(self.tab_result)
        # self.label_attendance_result.setGeometry(QtCore.QRect(10, -1, 371, 21))
        # self.label_attendance_result.setObjectName("label_attendance_result")
        self.button_confirm_attendance = QtWidgets.QPushButton(self.tab_result)
        self.button_confirm_attendance.setGeometry(QtCore.QRect(480, 421, 171, 51))
        self.button_confirm_attendance.setObjectName("button_confirm_attendance")
        self.gb_attendance_settings = QtWidgets.QGroupBox(self.tab_result)
        self.gb_attendance_settings.setGeometry(QtCore.QRect(10, 420, 461, 51))
        self.gb_attendance_settings.setObjectName("gb_attendance_settings")
        self.label_set_percentage = QtWidgets.QLabel(self.gb_attendance_settings)
        self.label_set_percentage.setGeometry(QtCore.QRect(10, 20, 181, 21))
        self.label_set_percentage.setObjectName("label_set_percentage")
        self.sb_percentage = QtWidgets.QDoubleSpinBox(self.gb_attendance_settings)
        self.sb_percentage.setGeometry(QtCore.QRect(190, 20, 61, 20))
        self.sb_percentage.setMaximum(100.00)
        self.sb_percentage.setObjectName("sb_percentage")
        self.cb_automatic_confirmation = QtWidgets.QCheckBox(self.gb_attendance_settings)
        self.cb_automatic_confirmation.setGeometry(QtCore.QRect(260, 20, 191, 21))
        self.cb_automatic_confirmation.setObjectName("check_automatic_confirmation")
        self.gb_attendance_records = QtWidgets.QGroupBox(self.tab_result)
        self.gb_attendance_records.setGeometry(QtCore.QRect(0, 0, 661, 421))
        self.gb_attendance_records.setObjectName("gb_attendance_records")
        self.table_attendance_result = QtWidgets.QTableWidget(self.gb_attendance_records)
        self.table_attendance_result.setGeometry(QtCore.QRect(10, 50, 641, 361))
        self.table_attendance_result.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_attendance_result.setAlternatingRowColors(False)
        self.table_attendance_result.setSortingEnabled(False)
        self.table_attendance_result.setObjectName("table_attendance_result")
        self.cb_choose_records = QtWidgets.QComboBox(self.gb_attendance_records)
        self.cb_choose_records.setGeometry(QtCore.QRect(100, 20, 241, 22))
        self.cb_choose_records.setObjectName("cb_choose_records")
        self.label_current_records = QtWidgets.QLabel(self.gb_attendance_records)
        self.label_current_records.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_current_records.setObjectName("label_current_records")
        self.label_date_of_record = QtWidgets.QLabel(self.gb_attendance_records)
        self.label_date_of_record.setGeometry(QtCore.QRect(350, 20, 31, 16))
        self.label_date_of_record.setObjectName("label_date_of_record")
        self.label_time_of_record = QtWidgets.QLabel(self.gb_attendance_records)
        self.label_time_of_record.setGeometry(QtCore.QRect(510, 20, 41, 16))
        self.label_time_of_record.setObjectName("label_time_of_record")
        self.label_current_date = QtWidgets.QLabel(self.gb_attendance_records)
        self.label_current_date.setGeometry(QtCore.QRect(390, 20, 111, 16))
        self.label_current_date.setText("")
        self.label_current_date.setObjectName("label_current_date")
        self.label_current_time = QtWidgets.QLabel(self.gb_attendance_records)
        self.label_current_time.setGeometry(QtCore.QRect(550, 20, 101, 16))
        self.label_current_time.setText("")
        self.label_current_time.setObjectName("label_current_time")
        self.tabWidget.addTab(self.tab_result, "")
        window_main.setCentralWidget(self.centralwidget)

        self.retranslateUi(window_main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window_main)

    def retranslateUi(self, window_main):
        _translate = QtCore.QCoreApplication.translate
        window_main.setWindowTitle(_translate("window_main", "Система автоматизированного контроля посещаемости"))
        self.label_camera_output_title.setText(_translate("window_main", "Запись с камеры:"))
        self.gb_recording.setTitle(_translate("window_main", "Ведение контроля"))
        self.button_toggle_recording.setText(_translate("window_main", "Начать работу"))
        self.label_status_title.setText(_translate("window_main", "Состояние:"))
        self.label_status_current.setText(_translate("window_main", ""))
        self.label_camera_output.setText(_translate("window_main", "Camera Output"))
        self.gb_classroom.setTitle(_translate("window_main", "Аудитория"))
        self.label_choose_classroom.setText(_translate("window_main", "Выбор аудитории:"))
        self.button_confirm_classroom.setText(_translate("window_main", "Подтвердить выбранную аудиторию"))
        self.gb_camera.setTitle(_translate("window_main", "Камера"))
        self.label_choose_camera.setText(_translate("window_main", "Выбор камеры:"))
        self.button_refresh_camera_list.setText(_translate("window_main", "Обновить список камер"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), _translate("window_main", "Управление"))
        self.cb_automatic_confirmation.setText(_translate("window_main", "Фиксировать посещаемость автоматически"))
        self.button_confirm_attendance.setText(_translate("window_main", "Подтвердить посещаемость"))
        self.gb_attendance_settings.setTitle(_translate("window_main", "Настройки контроля посещаемости"))
        self.label_set_percentage.setText(_translate("window_main", "Требуемый процент обнаружения:"))
        self.cb_automatic_confirmation.setText(_translate("window_main", "Фиксировать без подтверждения"))
        self.gb_attendance_records.setTitle(_translate("window_main", "Отчёт о посещаемости"))
        self.label_current_records.setText(_translate("window_main", "Текущий отчёт:"))
        self.label_date_of_record.setText(_translate("window_main", "Дата:"))
        self.label_time_of_record.setText(_translate("window_main", "Время:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_result), _translate("window_main", "Отчёт"))
